### ISSUE TITLE
Capturing Change Data from Delta notebooks are only HTML code

### ISSUE THREAD

**Issue by datasharkNL** [databricks/tech-talks#31]
Can you please add the notebooks? Now there are only HTML files.

Please provide scala or python notebooks

**Comment by dennyglee** [comment]
Oh, if you import the notebooks into Databricks Community Edition, you can then read them in DBCE and export them to Scala or Python.  Would that work?  It's harder for us to maintain multiple versions hence usually we go with ipynb or HTML so you  can see the notebook without importing it.

**Comment by dennyglee** [comment]
Hi @datasharkNL - does this help solve your issue?  Please re-open and clarify it not.  Thanks!
