### ISSUE TITLE
Upload POS Streaming Dataset to tech-talks/datasets

### ISSUE THREAD

**Issue by bryansmith-db** [databricks/tech-talks#79]
Need to add the attached file to the datasets folder for use with the point-of-sale streaming solution accelerator
[point_of_sale_simulated.zip](https://github.com/databricks/tech-talks/files/6964543/point_of_sale_simulated.zip)

**Comment by dennyglee** [comment]
Confirming that this dataset is manually generated for open-source usage?  (by default Apache 2.0 license)?

**Comment by bryansmith-db** [comment]
Yes.  It is a simulated dataset that I generated based on random numbers.  It is available for open-source usage.

**Comment by dennyglee** [comment]
Uploaded at: https://github.com/databricks/tech-talks/blob/master/datasets/point_of_sale_simulated.zip
